import DocsLayout from '@/components/DocsLayout'
import Callout from '@/components/Callout'
import CodeBlock from '@/components/CodeBlock'
import Link from 'next/link'

export const metadata = { title: 'Installation' }

export default function InstallationPage() {
  return (
    <DocsLayout>
      <div className="docs-prose">
        <span className="inline-block text-[10px] font-semibold text-[var(--text-secondary)] bg-[var(--tag-bg)] px-2.5 py-1 rounded uppercase tracking-wider mb-4">
          Getting Started
        </span>
        <h1>Installation</h1>
        <p>
          Cleanmails runs as a Docker Compose stack on any Linux VPS. This page covers the full manual installation 
          process. For the fastest path, see <Link href="/quick-deploy">Quick Deploy</Link>.
        </p>

        <h2>System Requirements</h2>
        <table>
          <thead><tr><th>Component</th><th>Minimum</th><th>Recommended</th></tr></thead>
          <tbody>
            <tr><td>OS</td><td>Ubuntu 22.04 / Debian 12</td><td>Ubuntu 22.04 LTS</td></tr>
            <tr><td>CPU</td><td>1 vCPU</td><td>4 vCPU</td></tr>
            <tr><td>RAM</td><td>1 GB</td><td>4 GB</td></tr>
            <tr><td>Disk</td><td>5 GB SSD</td><td>50 GB SSD</td></tr>
            <tr><td>Network</td><td colSpan={2}>Outbound port 25 must be unblocked</td></tr>
          </tbody>
        </table>

        <h2>Manual Installation</h2>

        <h3>1. Install Docker</h3>
        <CodeBlock language="bash" code={`curl -fsSL https://get.docker.com | sh
systemctl enable docker
systemctl start docker`} />

        <h3>2. Create the application directory</h3>
        <CodeBlock language="bash" code={`mkdir -p /opt/cleanmails
cd /opt/cleanmails`} />

        <h3>3. Create the environment file</h3>
        <CodeBlock language="bash" filename="/opt/cleanmails/.env" code={`# Domain
DOMAIN=app.yourdomain.com

# Database
DB_PASSWORD=$(openssl rand -hex 16)
DATABASE_URL=postgres://cleanmails:\${DB_PASSWORD}@postgres:5432/cleanmails?sslmode=disable

# Redis
REDIS_URL=redis://redis:6379

# Security (REQUIRED — auto-generated by installer)
ENCRYPTION_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)

# App
BASE_URL=https://app.yourdomain.com
API_PORT=8080
GIN_MODE=release
ALLOWED_ORIGINS=https://app.yourdomain.com`} />

        <Callout type="warning" title="Generate unique secrets">
          <p>Run <code>openssl rand -hex 32</code> to generate the ENCRYPTION_KEY and JWT_SECRET. Never reuse keys across instances. The ENCRYPTION_KEY encrypts all sender passwords and integration tokens using AES-256-GCM.</p>
        </Callout>

        <h3>4. Create docker-compose.prod.yml</h3>
        <p>Copy the production docker compose file from your download. It includes six services:</p>
        <table>
          <thead><tr><th>Service</th><th>Purpose</th></tr></thead>
          <tbody>
            <tr><td><code>postgres</code></td><td>PostgreSQL 16 database</td></tr>
            <tr><td><code>redis</code></td><td>Redis 7 for task queue (Asynq)</td></tr>
            <tr><td><code>api</code></td><td>Go API server (Gin framework)</td></tr>
            <tr><td><code>worker</code></td><td>Background job processor</td></tr>
            <tr><td><code>frontend</code></td><td>Next.js React dashboard</td></tr>
            <tr><td><code>caddy</code></td><td>Reverse proxy + auto SSL</td></tr>
          </tbody>
        </table>

        <h3>5. Build Docker images</h3>
        <CodeBlock language="bash" code={`# Build the API server
docker build -t cleanmails-api:latest -f Dockerfile.api .

# Build the background worker
docker build -t cleanmails-worker:latest -f Dockerfile.worker .

# Build the frontend
docker build -t cleanmails-frontend:latest -f Dockerfile.frontend .`} />

        <h3>6. Configure firewall</h3>
        <CodeBlock language="bash" code={`ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 25/tcp
echo "y" | ufw enable`} />

        <h3>7. Start the stack</h3>
        <CodeBlock language="bash" code={`docker compose -f docker-compose.prod.yml up -d`} />

        <h3>8. Verify</h3>
        <CodeBlock language="bash" code={`# Check all containers are running
docker compose -f docker-compose.prod.yml ps

# Check health endpoint
curl http://localhost:8080/health

# Check logs
docker compose -f docker-compose.prod.yml logs -f api`} />

        <h2>SSL Configuration</h2>
        <p>The included Caddy container handles SSL automatically. Point your domain&apos;s A record to your server IP. The installer generates a <code>Caddyfile</code> that routes:</p>

        <CodeBlock language="text" filename="Caddyfile" code={`yourdomain.com {
    handle /api/* {
        reverse_proxy api:8080
    }
    handle /health {
        reverse_proxy api:8080
    }
    handle /t/* {
        reverse_proxy api:8080
    }
    handle /unsubscribe/* {
        reverse_proxy api:8080
    }
    handle {
        reverse_proxy frontend:3000
    }
    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Strict-Transport-Security "max-age=31536000"
    }
}`} />

        <p>Caddy will auto-provision a Let&apos;s Encrypt certificate on first request.</p>

        <h2>Updating</h2>
        <CodeBlock language="bash" code={`cd /opt/cleanmails
bash scripts/update.sh`} />

        <p>The update script downloads the latest release from S3, rebuilds all Docker images, and restarts the stack with zero downtime. You can also trigger updates from the admin panel (Settings → System → Check for Updates).</p>
      </div>
    </DocsLayout>
  )
}
