import type { MetadataRoute } from 'next'

const pages = [
  '/',
  '/installation',
  '/quick-deploy',
  '/first-login',
  '/license',
  '/validation/overview',
  '/validation/levels',
  '/campaigns/creating',
  '/campaigns/sequences',
  '/campaigns/scheduling',
  '/campaigns/ab-testing',
  '/campaigns/personalization',
  '/campaigns/ai-tags',
  '/campaigns/tracking',
  '/infrastructure/domains',
  '/infrastructure/dns',
  '/infrastructure/senders',
  '/infrastructure/warmup',
  '/infrastructure/rotation',
  '/lists/uploading',
  '/lists/validation',
  '/lists/managing',
  '/workspaces',
  '/teams',
  '/client-portal',
  '/ai/copilot',
  '/ai/mcp',
  '/integrations/webhooks',
  '/integrations/crm',
  '/integrations/slack',
  '/api/authentication',
  '/api/verification',
  '/api/outreach',
  '/api/workspaces',
  '/config/env-variables',
  '/config/docker',
  '/config/security',
  '/operations/monitoring',
  '/operations/backups',
  '/operations/updates',
  '/operations/troubleshooting',
]

export default function sitemap(): MetadataRoute.Sitemap {
  return pages.map((page) => ({
    url: `https://cleanmails.online/docs${page === '/' ? '' : page}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: page === '/' ? 1 : 0.8,
  }))
}
