import DocsLayout from '@/components/DocsLayout'
import Callout from '@/components/Callout'
import CodeBlock from '@/components/CodeBlock'

export const metadata = { title: 'Environment Variables' }

export default function EnvVariablesPage() {
  return (
    <DocsLayout>
      <div className="docs-prose">
        <span className="inline-block text-[10px] font-semibold text-[var(--text-secondary)] bg-[var(--tag-bg)] px-2.5 py-1 rounded uppercase tracking-wider mb-4">
          Configuration
        </span>
        <h1>Environment Variables</h1>
        <p>
          Cleanmails is configured entirely through environment variables. These are set in your <code>.env</code> file 
          (located at <code>/opt/cleanmails/.env</code> after installation).
        </p>

        <Callout type="warning" title="ENCRYPTION_KEY is required">
          <p>The <code>ENCRYPTION_KEY</code> must be a 64-character hex string (32 bytes). It&apos;s used for AES-256-GCM encryption of all sender passwords and integration tokens. Generate with: <code>openssl rand -hex 32</code></p>
        </Callout>

        <h2>Full Example</h2>
        <CodeBlock language="bash" filename="/opt/cleanmails/.env" code={`# Domain
DOMAIN=app.yourdomain.com

# Database
DB_PASSWORD=your-generated-password
DATABASE_URL=postgres://cleanmails:\${DB_PASSWORD}@postgres:5432/cleanmails?sslmode=disable

# Redis
REDIS_URL=redis://redis:6379

# Security
ENCRYPTION_KEY=your-64-hex-char-key-here
JWT_SECRET=your-jwt-secret-here

# App
BASE_URL=https://app.yourdomain.com
API_PORT=8080
GIN_MODE=release
ALLOWED_ORIGINS=https://app.yourdomain.com`} />

        <h2>Core Settings</h2>
        <table>
          <thead>
            <tr><th>Variable</th><th>Default</th><th>Description</th></tr>
          </thead>
          <tbody>
            <tr><td><code>DOMAIN</code></td><td>—</td><td>Your domain name (used by Caddy for SSL provisioning)</td></tr>
            <tr><td><code>DATABASE_URL</code></td><td>—</td><td><strong>Required.</strong> PostgreSQL connection string</td></tr>
            <tr><td><code>REDIS_URL</code></td><td>redis://localhost:6379</td><td>Redis connection URL (used by Asynq task queue)</td></tr>
            <tr><td><code>API_PORT</code></td><td>8080</td><td>Port the API server listens on</td></tr>
            <tr><td><code>BASE_URL</code></td><td>http://localhost:8080</td><td>Public URL of your instance (used in tracking links, unsubscribe URLs)</td></tr>
            <tr><td><code>GIN_MODE</code></td><td>debug</td><td>Set to <code>release</code> in production (disables debug logging)</td></tr>
            <tr><td><code>ALLOWED_ORIGINS</code></td><td>http://localhost:3000</td><td>Comma-separated list of allowed CORS origins</td></tr>
          </tbody>
        </table>

        <h2>Security</h2>
        <table>
          <thead>
            <tr><th>Variable</th><th>Description</th></tr>
          </thead>
          <tbody>
            <tr><td><code>ENCRYPTION_KEY</code></td><td><strong>Required.</strong> 64-char hex string for AES-256-GCM encryption of credentials</td></tr>
            <tr><td><code>JWT_SECRET</code></td><td><strong>Required.</strong> Secret key for signing JWT tokens (7-day expiry)</td></tr>
            <tr><td><code>DB_PASSWORD</code></td><td>PostgreSQL password (used in DATABASE_URL and by the postgres container)</td></tr>
          </tbody>
        </table>

        <h2>Database</h2>
        <table>
          <thead>
            <tr><th>Variable</th><th>Default</th><th>Description</th></tr>
          </thead>
          <tbody>
            <tr><td><code>DB_PASSWORD</code></td><td>—</td><td>PostgreSQL password (shared between app and postgres container)</td></tr>
            <tr><td><code>DATABASE_URL</code></td><td>—</td><td>Full PostgreSQL connection string with sslmode</td></tr>
            <tr><td><code>REDIS_URL</code></td><td>redis://redis:6379</td><td>Redis URL for Asynq background jobs</td></tr>
          </tbody>
        </table>

        <h2>Frontend</h2>
        <table>
          <thead>
            <tr><th>Variable</th><th>Default</th><th>Description</th></tr>
          </thead>
          <tbody>
            <tr><td><code>NEXT_PUBLIC_API_URL</code></td><td>http://localhost:8080</td><td>API URL the frontend uses (set to your public URL in production)</td></tr>
            <tr><td><code>HOSTNAME</code></td><td>0.0.0.0</td><td>Frontend listen host</td></tr>
            <tr><td><code>PORT</code></td><td>3000</td><td>Frontend listen port</td></tr>
          </tbody>
        </table>

        <Callout type="info" title="Auto-generated by installer">
          <p>The install script (<code>install.sh</code>) automatically generates all secrets using <code>openssl rand -hex</code>. You only need to provide the <code>--domain</code> flag. The generated <code>.env</code> file is set to mode 640 for security.</p>
        </Callout>

        <h2>Worker Configuration</h2>
        <p>The background worker connects to the same PostgreSQL and Redis instances. Worker behavior is configured through the Asynq server settings in code:</p>
        <table>
          <thead>
            <tr><th>Setting</th><th>Value</th><th>Description</th></tr>
          </thead>
          <tbody>
            <tr><td>Concurrency</td><td>10</td><td>Total concurrent task processors</td></tr>
            <tr><td>Critical queue weight</td><td>6</td><td>Bounce/complaint handling priority</td></tr>
            <tr><td>Default queue weight</td><td>3</td><td>Campaign dispatch, validation tasks</td></tr>
            <tr><td>Low queue weight</td><td>1</td><td>IMAP sync, AI replies</td></tr>
          </tbody>
        </table>

        <h2>Docker Resource Limits</h2>
        <p>The production Docker Compose sets memory limits per service:</p>
        <table>
          <thead>
            <tr><th>Service</th><th>Memory Limit</th></tr>
          </thead>
          <tbody>
            <tr><td>PostgreSQL</td><td>512 MB</td></tr>
            <tr><td>Redis</td><td>192 MB</td></tr>
            <tr><td>API Server</td><td>256 MB</td></tr>
            <tr><td>Worker</td><td>256 MB</td></tr>
            <tr><td>Frontend</td><td>256 MB</td></tr>
            <tr><td>Caddy</td><td>64 MB</td></tr>
          </tbody>
        </table>
      </div>
    </DocsLayout>
  )
}
